//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olx.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Errors() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olx.BLL.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action blocked.
        /// </summary>
        public static string ActionBlocked {
            get {
                return ResourceManager.GetString("ActionBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advert is blocked.
        /// </summary>
        public static string AdvertIsBlocked {
            get {
                return ResourceManager.GetString("AdvertIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current password is not valid.
        /// </summary>
        public static string CurrentPasswordIsNotValid {
            get {
                return ResourceManager.GetString("CurrentPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email already in use.
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error authorized user.
        /// </summary>
        public static string ErrorAthorizedUser {
            get {
                return ResourceManager.GetString("ErrorAthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image sizes not initializing.
        /// </summary>
        public static string ImageSizesInitError {
            get {
                return ResourceManager.GetString("ImageSizesInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error read image sizes.
        /// </summary>
        public static string ImageSizesReadError {
            get {
                return ResourceManager.GetString("ImageSizesReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InvalidAdminMessageId.
        /// </summary>
        public static string InvalidAdminMessageId {
            get {
                return ResourceManager.GetString("InvalidAdminMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid advert id.
        /// </summary>
        public static string InvalidAdvertId {
            get {
                return ResourceManager.GetString("InvalidAdvertId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid area ref.
        /// </summary>
        public static string InvalidAreaRef {
            get {
                return ResourceManager.GetString("InvalidAreaRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid category id.
        /// </summary>
        public static string InvalidCategoryId {
            get {
                return ResourceManager.GetString("InvalidCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid chat id.
        /// </summary>
        public static string InvalidChatId {
            get {
                return ResourceManager.GetString("InvalidChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid chatt id.
        /// </summary>
        public static string InvalidChattId {
            get {
                return ResourceManager.GetString("InvalidChattId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation data error.
        /// </summary>
        public static string InvalidConfirmationData {
            get {
                return ResourceManager.GetString("InvalidConfirmationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на fdghdfghhfd.
        /// </summary>
        public static string Invalidfghbsdfghdfg {
            get {
                return ResourceManager.GetString("Invalidfghbsdfghdfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid filter creation model data.
        /// </summary>
        public static string InvalidFilterCreationModelData {
            get {
                return ResourceManager.GetString("InvalidFilterCreationModelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid filter id.
        /// </summary>
        public static string InvalidFilterId {
            get {
                return ResourceManager.GetString("InvalidFilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid filter value id.
        /// </summary>
        public static string InvalidFilterValueId {
            get {
                return ResourceManager.GetString("InvalidFilterValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невірний логін або пароль.
        /// </summary>
        public static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid region ref.
        /// </summary>
        public static string InvalidRegionRef {
            get {
                return ResourceManager.GetString("InvalidRegionRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid reser password data.
        /// </summary>
        public static string InvalidResetPasswordData {
            get {
                return ResourceManager.GetString("InvalidResetPasswordData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid role name.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid settlement id.
        /// </summary>
        public static string InvalidSettlementId {
            get {
                return ResourceManager.GetString("InvalidSettlementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid settlement ref.
        /// </summary>
        public static string InvalidSettlementRef {
            get {
                return ResourceManager.GetString("InvalidSettlementRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid user email.
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid user id.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error read JWT setting.
        /// </summary>
        public static string JwtSettingsReadError {
            get {
                return ResourceManager.GetString("JwtSettingsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New post data update error.
        /// </summary>
        public static string NewPostDataUpdateError {
            get {
                return ResourceManager.GetString("NewPostDataUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New post request error.
        /// </summary>
        public static string NewPostRequestError {
            get {
                return ResourceManager.GetString("NewPostRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reCapthca validation error.
        /// </summary>
        public static string ReCapthcaValidationError {
            get {
                return ResourceManager.GetString("ReCapthcaValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User creation error.
        /// </summary>
        public static string UserCreateError {
            get {
                return ResourceManager.GetString("UserCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User remove error.
        /// </summary>
        public static string UserRemoveError {
            get {
                return ResourceManager.GetString("UserRemoveError", resourceCulture);
            }
        }
    }
}
